### ISSUE TITLE
Ausdrucken der Messwerte 

### ISSUE THREAD

**Issue by vonSeck** [tms-hl/schilfprojekt#13]
Um die Werte der Wasseranalyse (Oberflächenwasser und Sedimentwasser) auf Stimmigkeit zu prüfen und kennzeichnen zu können, benötigen wir einen Ausdruck aller Werte. Ist dies möglich? 
Zusätzlich brauchen wir auch alle Schilfvermessungswerte - und zwar die Einzelwerte.

Eine baldige Rückmeldung wäre super. Und falls Ausdruck problemlos möglich, bitte in meinem Fach im Lehrerzimmer hinterlegen.
Danke.

**Comment by Joogle** [comment]
Ist gut Möglich. Soll es mehrfach gedruckt werden? Dann würde es eventuell mehr Sinn machen nur die PDF zu haben und nach Bedarf zu Drucken, statt den Stapel Papier einscannen zu müssen um zu drucken?

**Comment by Joogle** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/10084110/5919044/dae74c3a-a62f-11e4-9226-f1446c280895.png)
Ist das so richtig oder muss das noch anders?

**Comment by vonSeck** [comment]
Wenn möglich, auch die Einheiten ausweisen. Lassen sich die Markierungen für die Sommer- bzw. Herbstmessungen mit übernehmen? Für die Schilfuntersuchungen (sind ja nur im Herbst) dann bitte alle Einzelwerte (mit Einheit).

Anzahl der Ausdrucke: 3. 

 

Gibt es eine Möglichkeit euch namentlich anzureden? Es ist eigenartig so anonym zu kooperieren.

Freundliche Grüße

U. von Seck

 

Von: Joogle [mailto:notifications@github.com] 
Gesendet: Dienstag, 27. Januar 2015 14:24
An: tms-hl/schilfprojekt
Cc: Ulrike von Seck
Betreff: Re: [schilfprojekt] Ausdrucken der Messwerte (#13)

 

 <https://cloud.githubusercontent.com/assets/10084110/5919044/dae74c3a-a62f-11e4-9226-f1446c280895.png> unbenannt
Ist das so richtig oder muss das noch anders?

**Comment by Joogle** [comment]
Wie dringend werden die Drucke benötigt?
Ich habe mir das angeguckt und sowohl die Farben als auch die Einheiten sind nicht in der Datenbank festgelegt, sondern werden mit PHP als HTML Code erzeugt.
Ich könnte entweder eine Druckversion der Seite erstellen, die ein Drucken der Tabelle direkt über den Browser ermöglicht. Das wäre elegant, ein nützliches Feature für alle Besucher der Seite und eine schöne Aufgabe für die ich schon einen Ansatz hätte. Es würde allerdings etwas länger dauern. Daher gibt es bei Zeitdruck die Alternative es als Excel Dokument zu exportieren und Einheiten und Farben händisch einzufügen.
Grüße
Jannes

**Comment by vonSeck** [comment]
Eine Druckversion der Seite anzubieten, ist eine prima Idee. Es wäre schön, wenn die Ausdrucke im März vorliegen. Sollte ein früherer Termin für die  Ausdruck notwendig werden, melde ich mich. 

Danke. 

Grüße

U. von Seck

 

Von: Joogle [mailto:notifications@github.com] 
Gesendet: Samstag, 31. Januar 2015 15:47
An: tms-hl/schilfprojekt
Cc: Ulrike von Seck
Betreff: Re: [schilfprojekt] Ausdrucken der Messwerte (#13)

 

Wie dringend werden die Drucke benötigt?
Ich habe mir das angeguckt und sowohl die Farben als auch die Einheiten sind nicht in der Datenbank festgelegt, sondern werden mit PHP als HTML Code erzeugt.
Ich könnte entweder eine Druckversion der Seite erstellen, die ein Drucken der Tabelle direkt über den Browser ermöglicht. Das wäre elegant, ein nützliches Feature für alle Besucher der Seite und eine schöne Aufgabe für die ich schon einen Ansatz hätte. Es würde allerdings etwas länger dauern. Daher gibt es bei Zeitdruck die Alternative es als Excel Dokument zu exportieren und Einheiten und Farben händisch einzufügen.
Grüße
Jannes

**Comment by vonSeck** [comment]
Habe den Termin bezüglich Ausdruck noch mal mit Herrn Clement abgeklärt: März ist in Ordnung. Er fänd es gut, wenn auch eine Excel-Version vorliegen würde. 

Danke. 

Freundliche Grüße

U. von Seck

 

Von: Joogle [mailto:notifications@github.com] 
Gesendet: Samstag, 31. Januar 2015 15:47
An: tms-hl/schilfprojekt
Cc: Ulrike von Seck
Betreff: Re: [schilfprojekt] Ausdrucken der Messwerte (#13)

 

Wie dringend werden die Drucke benötigt?
Ich habe mir das angeguckt und sowohl die Farben als auch die Einheiten sind nicht in der Datenbank festgelegt, sondern werden mit PHP als HTML Code erzeugt.
Ich könnte entweder eine Druckversion der Seite erstellen, die ein Drucken der Tabelle direkt über den Browser ermöglicht. Das wäre elegant, ein nützliches Feature für alle Besucher der Seite und eine schöne Aufgabe für die ich schon einen Ansatz hätte. Es würde allerdings etwas länger dauern. Daher gibt es bei Zeitdruck die Alternative es als Excel Dokument zu exportieren und Einheiten und Farben händisch einzufügen.
Grüße
Jannes

**Comment by Joogle** [comment]
Die Druckfunktion ist schon einwandfrei nutzbar, es fehlen nur noch optische Details.
Was die Excel Tabelle betrifft: Sie ist einfach zu erstellen, aber ich würde bei ihr aus Zeitgründen lieber auf die Farbe verzichten.
Grüße
Jannes
![image](https://cloud.githubusercontent.com/assets/10084110/6096777/eaece7d4-afa3-11e4-8490-f6ac612a458c.png)

![image](https://cloud.githubusercontent.com/assets/10084110/6096775/d200fe90-afa3-11e4-8067-fbda36210e23.png)

**Comment by vonSeck** [comment]
Das ist ja prima. Wenn Ausdrucke schon möglich sind, bitte einmal ausdrucken, das Ganze dann 2x kopieren und anschließend im Sekretariat hinterlegen. Eine fehlende Farbmarkierung in Excel ist okay. Herzlichen Dank. Das klappt ja wunderbar.

Liebe Grüße

U. von Seck

 

Von: Joogle [mailto:notifications@github.com] 
Gesendet: Sonntag, 8. Februar 2015 15:07
An: tms-hl/schilfprojekt
Cc: Ulrike von Seck
Betreff: Re: [schilfprojekt] Ausdrucken der Messwerte (#13)

 

Die Druckfunktion ist schon einwandfrei nutzbar, es fehlen nur noch optische Details.
Was die Excel Tabelle betrifft: Sie ist einfach zu erstellen, aber ich würde bei ihr aus Zeitgründen lieber auf die Farbe verzichten.
Grüße
Jannes
 <https://cloud.githubusercontent.com/assets/10084110/6096777/eaece7d4-afa3-11e4-8490-f6ac612a458c.png> image

 <https://cloud.githubusercontent.com/assets/10084110/6096775/d200fe90-afa3-11e4-8067-fbda36210e23.png> image

**Comment by Joogle** [comment]
Ich habe die Tabelle gedruckt und im Sekretariat für Sie hinterlegt, allerdings konnte ich es nicht farbig ausdrucken, weil der Drucker im Sekretariat nicht funktioniert. Wenn es einen verfügbaren Stick gibt, auf den ich die Datei kopieren kann, kann ich das gerne machen.
Grüße Jannes

**Comment by vonSeck** [comment]
Hallo Jannes, 

danke für die Ausdrucke. Sind in schwarz-weiß völlig ausreichend. Bitte auch die Schilfvermessungsdaten ausdrucken und in mein Fach im Lehrerzimmer legen lassen.

Ein Stick ist ab morgen (mit meinem Namen beschriftet) im Sekretariat zur Speicherung hinterlegt. 

Liebe Grüße

U. von Seck

 

Von: Joogle [mailto:notifications@github.com] 
Gesendet: Dienstag, 10. Februar 2015 13:37
An: tms-hl/schilfprojekt
Cc: Ulrike von Seck
Betreff: Re: [schilfprojekt] Ausdrucken der Messwerte (#13)

 

Ich habe die Tabelle gedruckt und im Sekretariat für Sie hinterlegt, allerdings konnte ich es nicht farbig ausdrucken, weil der Drucker im Sekretariat nicht funktioniert. Wenn es einen verfügbaren Stick gibt, auf den ich die Datei kopieren kann, kann ich das gerne machen.
Grüße Jannes

**Comment by NiJoMa** [comment]
Ich denke dieses Thema kann bis zum nächsten Gebrauch geschlossen werden
