### ISSUE TITLE
Allgemeine Bildernamen

### ISSUE THREAD

**Issue by KlappiKlappstuhl** [tms-hl/schilfprojekt#14]
Wie sollen wir alle Bilder einheitlich benennen?
Also einige habe Zahlen vor dem Namen, andere haben ganz augeschrieben Namen und wieder andere nur Namensabkürzungen..
Bevorzug wäre es gut Zahlen vor dem Namen wegzulassen und alles mit Abkürzungen und ohne Lehrzeichen zu machen. Also bsp. AbsFrüMüg (Absalonshorst Frühling Müggenbusch)
Einige Dateinamen sind auch komisch...
Ich bitte Namenswüsche um einheitliche Namen zu erstellen!

**Comment by vonSeck** [comment]
Bitte Bezug auf die Auftrags-Nr. nehmen (mir fiel es gerade schwer zu erschließen, welche Bilder gemeint sind). Vermutlich ist hier das Hochladen weiterer Fotos gemeint zu Issue #4??

Gruß

U. von Seck

 

Von: KlappiKlappstuhl [mailto:notifications@github.com] 
Gesendet: Dienstag, 27. Januar 2015 15:10
An: tms-hl/schilfprojekt
Betreff: [schilfprojekt] Allgemeine Bildernamen (#14)

 

Wie sollen wir alle Bilder einheitlich benennen?
Also einige habe Zahlen vor dem Namen, andere haben ganz augeschrieben Namen und wieder andere nur Namensabkürzungen..
Bevorzug wäre es gut Zahlen vor dem Namen wegzulassen und alles mit Abkürzungen und ohne Lehrzeichen zu machen. Also bsp. AbsFrüMüg (Absalonshorst Frühling Müggenbusch)
Einige Dateinamen sind auch komisch...
Ich bitte Namenswüsche um einheitliche Namen zu erstellen!

**Comment by KlappiKlappstuhl** [comment]
Es geht allgemein um alle Bilder, weil es keine allgemeine Namensgebung gibt.

**Comment by NiJoMa** [comment]
Ist es ok wenn wir die Bilder nach folgendem Schema bennen?
Bilder der Wakenitz:
Abs(Standortkürzel)-08.2011(Monat und Jahr der Aufnahme)-1(Bildnummer bei mehreren Bildern)

Tiere/Zeichnungen/..:
Namen der Tiere/Zeichnungen verständlich abkürzen ggf. durchnummerieren

**Comment by vonSeck** [comment]
Prima, dass an der Seite gearbeitet wird!!!!

Auf den ersten Blick erscheint die Benennung logisch. Bin mir allerdings immer noch nicht sicher, welche Bilder neu benannt werden sollen. Bräuchte hierzu noch mal genauere Angaben oder ich komme am Dienstag um 13.30 Uhr kurz vorbei. -- Bei Abkürzungen sind Legenden immer wichtig. 

Liebe Grüße

U. von Seck

 

Von: NiJoMa [mailto:notifications@github.com] 
Gesendet: Freitag, 30. Januar 2015 20:40
An: tms-hl/schilfprojekt
Cc: Ulrike von Seck
Betreff: Re: [schilfprojekt] Allgemeine Bildernamen (#14)

 

Ist es ok wenn wir die Bilder nach folgendem Schema bennen?
Bilder der Wakenitz:
Abs(Standortkürzel)-08.2011(Monat und Jahr der Aufnahme)-1(Bildnummer bei mehreren Bildern)

Tiere/Zeichnungen/..:
Namen der Tiere/Zeichnungen verständlich abkürzen ggf. durchnummerieren

**Comment by KlappiKlappstuhl** [comment]
Gute Idee Nils!!
