### ISSUE TITLE
Ausdruck Messwerte

### ISSUE THREAD

**Issue by vonSeck** [tms-hl/schilfprojekt#19]
Herzlichen Dank für die Ausdrucke der Messwerte. Uns fehlt noch der Ausdruck der Sedimentwasseranalyse. Könnte ich diese einmal als Ausdruck und einmal per Mail erhalten?
Ich wünsche allen ein schönes Osterfest. 
Liebe Grüße
U. von Seck

**Comment by vonSeck** [comment]
BITTE AN DIE WERTE SEDIMENTWASSERANALYSE DENKEN!
SIE WERDEN NUN DRINGEND GEBRAUCHT! BITTE NOCH IN DIESER WOCHE IM SEKRETARIAT ABGEBEN UND ALS DATEI PER MAIL AN MICH.
Danke. 
U. von Seck

**Comment by Joogle** [comment]
Sorry ich hab das erst jetzt mitgekriegt tut mir wirklich Leid
Ich weiß auch grad nicht was genau jetzt gedruckt werden soll, bzw. was ich schon gedruckt hatte.

**Comment by Joogle** [comment]
Ich habe jetzt mal das als PDF gespeichert von dem ich glaube, dass Sie es meinen, ich habe aber Ihre E-Mail Adresse nicht. Wenn Sie mir die irgendwie mitteilen kann ich Ihnen die PDF Datei so schnell wie möglich schicken.
MfG
Jannes

**Comment by vonSeck** [comment]
Hallo Jannes, 

bitte den Ausdruck morgen im Sekretariat abgeben oder noch besser nach der 1. Stunde in der Bio-Sammlung. Habe zuvor oben im Chemie-Raum, komme dann aber zur Sammlung.

Gruß

U. von Seck

 

 

Von: Joogle [mailto:notifications@github.com] 
Gesendet: Samstag, 25. April 2015 18:56
An: tms-hl/schilfprojekt
Cc: Ulrike von Seck
Betreff: Re: [schilfprojekt] Ausdruck Messwerte (#19)

 

Ich habe jetzt mal das als PDF gespeichert von dem ich glaube, dass Sie es meinen, ich habe aber Ihre E-Mail Adresse nicht. Wenn Sie mir die irgendwie mitteilen kann ich Ihnen die PDF Datei so schnell wie möglich schicken.
MfG
Jannes

**Comment by vonSeck** [comment]
Hallo Lukas und Max, hallo Jannes, 

habe den Ausdruck der Sedimentwasseranalyse nach der 8. Stunde in meinem Fach gefunden. Danke dafür. 

Beim Vergleich mit den Werten der Internetseite fällt allerdings auf, dass die Werte nicht systematisch geordnet sind. So kann man leider nicht vernünftig die Werte kontrollieren. 

Nun noch einmal die dringende Bitte: Zusendung der Werte der Sedimentwasseranalyse – geordnet nach Standort – per Mail (Adresse ist nun bekannt), am besten natürlich als veränderbare Datei, falls das zügig machbar ist. Dies gilt auch für die anderen Daten (Wasseranalyse Oberflächenwasser, Schilfvermessung Mittelwerte, Schilfvermessung  Einzelwerte).

Liebe Grüße

Ulrike von Seck

 

 

Von: Joogle [mailto:notifications@github.com] 
Gesendet: Samstag, 25. April 2015 18:56
An: tms-hl/schilfprojekt
Cc: Ulrike von Seck
Betreff: Re: [schilfprojekt] Ausdruck Messwerte (#19)

 

Ich habe jetzt mal das als PDF gespeichert von dem ich glaube, dass Sie es meinen, ich habe aber Ihre E-Mail Adresse nicht. Wenn Sie mir die irgendwie mitteilen kann ich Ihnen die PDF Datei so schnell wie möglich schicken.
MfG
Jannes
