### ISSUE TITLE
Berechnung der Durchschnittswerte automatisieren

### ISSUE THREAD

**Issue by janneck** [tms-hl/schilfprojekt#2]
Die Berechnung von durchschnittlichen Halmmesswerten sollte durch geeignete SQL-Aggregatfunktionen gelöst werden.

**Comment by NiJoMa** [comment]
SELECT Standort,Datum, ROUND(AVG(LaengeUnterWasser),2) AS Unterwasserlänge,ROUND(AVG(LaengeUeberWasser),2) AS ueberwasserlänge,ROUND(AVG(LaengeGesamt),2) AS Gesamtlaenge,ROUND(AVG(DickeUnten),2) AS Halmdickeunten, ROUND(AVG(DickeMitte),2) AS Halmdickemitte ,ROUND(AVG(Blattbreite),2) AS Blattbreite,ROUND(AVG(Blattlaenge),2) AS Blattlaenge, ROUND(AVG(Blattzahl),2) AS Blattanzahl, ROUND(AVG(Rispenlaenge),2) As Rispenlaenge,ROUND(AVG(Nodienzahl),2) AS Nodienanzahl FROM biologischeeinzelmessergebnisse GROUP BY Standort, Datum

Wünschen sie sich das etwa so? Ich muss das ganze nur noch in die vermessung.php implementieren..

Nils

**Comment by NiJoMa** [comment]
SELECT Standort,Datum, ROUND(AVG(LaengeUnterWasser),2) AS Unterwasserlänge,ROUND(AVG(LaengeUeberWasser),2) AS ueberwasserlänge,ROUND(AVG(LaengeGesamt),2) AS Gesamtlaenge,ROUND(AVG(DickeUnten),2) AS Halmdickeunten, ROUND(AVG(DickeMitte),2) AS Halmdickemitte ,ROUND(AVG(Blattbreite),2) AS Blattbreite,ROUND(AVG(Blattlaenge),2) AS Blattlänge, ROUND(AVG(Blattzahl),2) AS Blattanzahl, ROUND(AVG(Rispenlaenge),2) As Rispenlänge,ROUND(AVG(Nodienzahl),2) AS Nodienanzahl FROM biologischeEinzelmessergebnisse GROUP BY Standort, Datum ORDER BY `biologischeEinzelmessergebnisse`.

Diese Funktion klappt nun auch
