### ISSUE TITLE
Fotografie Standort Wallbrechtbrücke 

### ISSUE THREAD

**Issue by vonSeck** [tms-hl/schilfprojekt#20]
Eure Idee, einen Schilfstandort im Jahresverlauf zu fotografieren, könnte jetzt starten: am Standort Wallbrechtbrücke sind die ersten Halme über Wasser zu sehen.
Eine monatliche Dokumentation vom gleichen Standort, aus dem gleihen Blickwinkel (Empfehlung von der Brücke herunter) wäre eine Berreichungerung der Internetseite. Also, nicht lange zögern: Wer übernimmt die Aufgabe???

Ich komme am Dienstag nach der 6. Stunde wieder im Informatikraum vorbei, vielleicht können wir ja schon auf programmiertechnische Fortschritte schauen?!
Liebe Grüße 
U. von Seck

**Comment by NiJoMa** [comment]
Lukas K. wollte das übernehmen.

**Comment by KlappiKlappstuhl** [comment]
Ich habe das übernommen und werde auch bald die nächsten Fotos machen.

**Comment by NiJoMa** [comment]
Projekt geschlossen
