### ISSUE TITLE
Treff am Dienstag

### ISSUE THREAD

**Issue by vonSeck** [tms-hl/schilfprojekt#21]
Liebe Schilf-Informatiker, 
am Dienstag bitte alle mal wieder Treff im Informatikraum - direkt nach der 6. Stunde, da ich in der 7. Stunde selbst wieder Unterricht habe. 
Bereitet kurze Berichte vor, woran ihr gerade arbeitet, damit wir den aktuellen Stand der Arbeiten mal im Überblick erfassen. 
Im Juni finden die nächsten Wakenitz-Untersuchungen statt. Bis dahin sollten eure Vorhaben Gestalt angenommen haben!
Bis dahin ein schönes Wochenende und einen netten 1. Mai.
Liebe Grüße
U. von Seck

**Comment by janneck** [comment]
Wir treffen uns im Gruppenraum 132, damit wir nicht immer mit ein paar Leuten den Computerraum belegen müssen. Der Gruppenraum wurde heute schon als (inoffizieller) Schilf-Raum eingerichtet :-)
