### ISSUE TITLE
Vorbereitung der Eintragungslisten

### ISSUE THREAD

**Issue by vonSeck** [tms-hl/schilfprojekt#22]
Im Juni werden neue Daten erhoben zur Wasseranalyse. Hierzu werden vormittags handschriftlich Protokolle geführt, die nachmittags in die Datenbank eingegeben werden müssen. 

Hierzu benötigen wir zwei Schüler, die sich in das Handling mit den Eintragungslisten einarbeiten und den Schülern der Q1-Bio-Profilklasse helfend zur Seite stehen.

Außerdem könnten diese Schüler Daten nachtragen, die vom letzten Jahr nicht in die Datenbank eingegeben worden sind. Wer dies übernehmen möchte, bitte bei mir melden oder am Dienstag (5.5.2015) bei der Besprechung mitteilen.

Liebe Grüße
Ulrike von Seck

**Comment by KlappiKlappstuhl** [comment]
wie sieht es jetzt hiermit aus??

**Comment by janneck** [comment]
Ist geklärt.
