### ISSUE TITLE
Wallbrechtbruecke statt Wakenitzbruecke

### ISSUE THREAD

**Issue by TomTomRixRix** [tms-hl/schilfprojekt#24]
Liebes Entwickler-Team,

Momentan können die Daten von dem Standort "Wallbrechtbrücke" nicht nachträglich im Admin-Bereich geändert werden, dies ist heute bei der Aktualisierung der chemischen Parameter / Wasseranalyse aufgefallen. 

Das Problem ist, dass in der "editchemdata.php" Datei in den Zeilen 84 und 89 noch der alte Name des Standortes verwendet wird, dieser jedoch nicht mehr in der Datenbank verwendet wird. "Wakenitzbruecke" muss also einfach in "Wallbrechtbruecke" geändert werden.

Dasselbe gilt für die edibiodata.php und die editbiomittel.php Dateien!

Wäre gut, wenn ihr das so schnell wie möglich beheben könntet, damit auch diese Daten aktualisiert werden können.

**Comment by Joogle** [comment]
Ich kann das machen und zusammen mit der inputchemdata pushen.

**Comment by TomTomRixRix** [comment]
Super, wenn du eh schon dabei bist, kannst du dann Issue 25 in der inputchemdata auch gleich lösen, damit wir morgen vielleicht sogar die neuen Browser verwenden können?
Des Rätsels Lösung steht auch schon in dem von mir geposteten Link.

Vielen Dank

**Comment by Joogle** [comment]
Ok müsst ich hinkriegen. Mir ist außerdem aufgefallen, dass die Formulare(zumindest bei mir)mit Chrome nicht, bzw. nur fehlerhaft angezeigt werden. Ich hab mir das aber noch nicht genauer angeguckt.

**Comment by TomTomRixRix** [comment]
Cool. Ich nutze kein Chrome, aber werde mir das auch mal anschauen. Am besten du erstellst ein neues Issue mit einem Screenshot, dann können wir es alle sehen.

**Comment by Joogle** [comment]
Bist du dir bei den Zeilen sicher? Oder soll das nur in dem einen if komplett ersetzt werden?
![image](https://cloud.githubusercontent.com/assets/10084110/8457621/b651d090-2012-11e5-9444-55b47b5b5ddc.png)

**Comment by TomTomRixRix** [comment]
So wie es auf dem screenshot ist, sieht es perfekt aus. Vorher waren es 84 und 89 jetzt wohl 85 und 90 weil irgendwo eine Zeile eingefügt wurde. 

Kannst du das in editbiodata und editbiomittel auch ändern? Die sind alle ziemlich ähnlich aufgebaut.

**Comment by janneck** [comment]
Ist gefixt, oder?

**Comment by TomTomRixRix** [comment]
Jo, ich habs gerade getestet und es läuft
