### ISSUE TITLE
Eingabemaske nimmt in den neusten Browsern keine Kommazahlen an

### ISSUE THREAD

**Issue by TomTomRixRix** [tms-hl/schilfprojekt#25]
Beim Aktualisieren der Daten ist uns heute noch aufgefallen, dass die neue Firefox-Version Kommazahlen als ungültigen Wert nicht annimmt in allen Formularen!
Da wir jedoch dringend auch Kommazahlen in die Datenbank einfügen und aktualisieren wollten, blieb uns nur übrig, den alten Internet-Explorer zu verwenden.

Da wir ja vor einem Jahr noch Kommazahlen eingeben konnten, war ich mir ziemlich sicher, dass sich etwas an dem Browser geändert hat. Und in der Tat hat meine Recherche ergeben, dass Firefox jetzt die HTML5 Standards bezüglich <input type"..."/> unterstützt. Dort haben wir type="number" stehen, was an sich auch nicht falsch ist, aber ohne Zusatz nur ganze Zahlen unterstützt. Hier könnt ihr selber lesen, warum das so ist und wie man es besser machen kann: https://blog.isotoma.com/2012/03/html5-input-typenumber-and-decimalsfloats-in-chrome/

Für die Dateneingabe am Donnerstag können wir übergangsweise eine alte Browserversion nehmen, aber langfristig sollte dies auch geändert werden!

**Comment by Joogle** [comment]
Werden nicht sowieso die Zahlen mit Punkt getrennt?

**Comment by TomTomRixRix** [comment]
Das stimmt, weil die Datenbank auf englisch läuft, aber trotzdem meckern die neuen Browser rum, dass Kommazahlen (ob mit Komma oder Punkt) ungültige Werte sind

**Comment by janneck** [comment]
Ist bereits gefixt.

**Comment by Joogle** [comment]
Ich glaube das ist nur bei der input chemdata gefixt. Die Biodaten Eingabefelder hatte ich jedenfalls noch nicht gemacht. ich wollte aber sowieso noch ein paar Optimierungen machen bei der inputchemdata, da kann ich die anderen auch schnell machen. Wobei die ja vielleicht auch mit Spannweiten versehen werden sollen?
