### ISSUE TITLE
Eingabemaske

### ISSUE THREAD

**Issue by Joogle** [tms-hl/schilfprojekt#26]
Ich bin durch mit der Eingabemaske. Ich muss nur noch schnell die Spannweiten eintragen. In 5 Minuten kann ich das pushen.

**Comment by TomTomRixRix** [comment]
Super, dann schreibe ich mal Herrn Janneck, dass du gleich fertig bist und ihm dann eine Mail schreibst, dass er den Code auf die live-Version kopieren kann!

**Comment by Joogle** [comment]
Ich hab seine E-Mail Adresse nicht. Habe jetzt ein Pull request geschickt.

**Comment by janneck** [comment]
Die Änderungen sind jetzt im aktuellen Branch.
