### ISSUE TITLE
Makrofauna 2014 ergänzen

### ISSUE THREAD

**Issue by vonSeck** [tms-hl/schilfprojekt#3]
Bitte ergänzt die Tabelle mit den tierischen Organismen Oktober 2014 und tragt diese unter Untersuchungen--> Makrofauna ein.

Datei bitte bei mir per Mail anfordern.

**Comment by luferix** [comment]
ich mach das

**Comment by NiJoMa** [comment]
Layout sollte noch verbessert werden

**Comment by KlappiKlappstuhl** [comment]
ist diese aufgabe jetzt erldigt lukas??
