### ISSUE TITLE
Änderung eines Wertes in der Datenbank

### ISSUE THREAD

**Issue by vonSeck** [tms-hl/schilfprojekt#31]
In der Datenbank ist ein bestimmter Wert zu ändern. Ich hinterlege den entsprechenden Wert Im Sekretariat in unserem Schilf-Fach. Bitte um zeitnahe Änderung.
U.v.Sk.

**Comment by luferix** [comment]
Der Wert lässt sich nur auf ganze Zahlen setzen, weil das formular an dieser Stelle falsch ist.
Ich habe den Wert zunächst auf 1 gesetzt, damit er nicht sofort auffällt.
Ich werde mich da nochmal mit Jannis zusammensetzen

**Comment by vonSeck** [comment]
Es ist gut, dass hier ein Fehler im Formular erkannt worden ist!! Aber bitte keine eigenständigen Änderungen vornehmen (also: Änderung wieder zurücksetzen). Es gibt sonst ein dramatisches Durcheinander, weil wir nicht mehr über Änderungen Protokoll führen können. 

Weiteres Vorgehen: mit Jannes bitte Problematik besprechen, ggf. unseren Neuzugang Lukas aus der Q2 oder beim Lias oder Tom R. um Hilfe bitten und dann den vorgegebenen Wert von Herrn Clement ändern. 

Dienstag ist unser nächstes Treffen. Ich bitte um vollständige Anwesenheit! 

An Lukas und Finn: Wie besprochen, bringe ich die Makrofauna-Unterlagen mit. 

 

 

Von: luferix [mailto:notifications@github.com] 
Gesendet: Dienstag, 15. September 2015 19:20
An: tms-hl/schilfprojekt
Cc: Ulrike von Seck
Betreff: Re: [schilfprojekt] Änderung eines Wertes in der Datenbank (#31)

 

Der Wert lässt sich nur auf ganze Zahlen setzen, weil das formular an dieser Stelle falsch ist.
Ich habe den Wert zunächst auf 1 gesetzt, damit er nicht sofort auffällt.
Ich werde mich da nochmal mit Jannis zusammensetzen

**Comment by Joogle** [comment]
Ich hab den Wert jetzt auf 0,046 gesetzt.
