### ISSUE TITLE
Dateinamen Web-freundlich umbenennen

### ISSUE THREAD

**Issue by janneck** [tms-hl/schilfprojekt#6]
Insbesondere im Download-Bereich sind viele Dateien mit Dateinamen, die plattformübergreifend Probleme bereiten können. Diese sollten umbenannt werden.

Dateinamen sollten grundsätzlich:
* keine Umlaute enthalten (ae statt ä, ss statt ß usw.),
* keine Leer- und Sonderzeichen außer _ und - enthalten,
* komplett klein geschrieben sein.

Die Änderung sollte idealerweise auf der Kommandozeile mit "git mv ..." gemacht werden.

Gleichzeitig müssen alle Links auf diese Dateien aktualisiert werden!

**Comment by DerSchmax** [comment]
ich mach das

**Comment by janneck** [comment]
Es sind jetzt schon viele Dateien umbenannt. Die Änderungen müssen aber auch im Downloadbereich nachvollzogen werden, d.h. die Links dort müssen auf die neuen Dateinamen verweisen. Bitte dringend ändern!

**Comment by NiJoMa** [comment]
Ist für die neue Website nicht mehr relevant
