### ISSUE TITLE
Dokumente in PDF umwandeln

### ISSUE THREAD

**Issue by janneck** [tms-hl/schilfprojekt#7]
Gerade im Downloadbereich sind viele PowerPoint- und Word-Dokumente zu finden. Diese sollten möglichst ins PDF umgewandelt werden, wenn die Bearbeitbarkeit nicht zwingend notwendig ist. (Man kann nicht voraussetzen, dass auf allen Geräten MS Office installiert ist.)

**Comment by Joogle** [comment]
Done
