### ISSUE TITLE
Entwicklung einer Übersicht als Bestimmungsschlüssel

### ISSUE THREAD

**Issue by vonSeck** [tms-hl/schilfprojekt#8]
Um die wirbellosen Tiere leichter bestimmen zu können, möchten wir einen sogenannten Bestimmungsschlüssel aufbauen. Hierbei sollen Fotos der Tiere (mit Angabe des Fotografen, des Fundortes und des Aufnahmedatums bzw. der Quelle) und ein kurzer, beschreibender Text dargestellt werden. Erste Fotos sind da: 4 Fotos von 3 Wirbellosen.
Bitte entwickelt eine Darstellungsmaske für den Bestimmungsschlüssel, der sich dann nach und nach füllt.

Einbindung wäre dann unter Untersuchungen-Makrofauna-Methoden sinnvoll.

Fotos (mit Tiernamen und Angabe Fundort, Datum und Fotograf) bitte bei mir per Mail anfordern.

https://github.com/tms-hl/schilfprojekt/issues/new#

**Comment by NiJoMa** [comment]
Der Bestimmungsschlüssel ist nun unter http://tms-hl.de/schilfprojekt_neu/wiki/doku.php?id=bestimmungsschluessel einsehbar. Achtung dies ist nicht!!! die Endversion und soll legendlich einen ersten Einblick bieten.

INFO: Der iFrame ist nun völlig flexibel.
